name: 'Set up Nullstone'
description: 'Set up Nullstone and add it to the PATH'
author: 'Nullstone'
branding:
  icon: arrow-down-circle
  color: blue
inputs:
  nullstone-version:
    description: 'The Nullstone CLI version to download and use.'
    required: false
    default: 'latest'
runs:
  using: node20
  main: dist/index.js
  post-if: success()
